// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 7/11/2026, 10:20:44 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg3 from "./../../assets/css/tailwind.config.js";
const config = [
{"content":{"files":["/Applications/XAMPP/xamppfiles/htdocs/buyer-project/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Applications/XAMPP/xamppfiles/htdocs/buyer-project/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Applications/XAMPP/xamppfiles/htdocs/buyer-project/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Applications/XAMPP/xamppfiles/htdocs/buyer-project/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Applications/XAMPP/xamppfiles/htdocs/buyer-project/plugins/**/*.{js,ts,mjs}","/Applications/XAMPP/xamppfiles/htdocs/buyer-project/composables/**/*.{js,ts,mjs}","/Applications/XAMPP/xamppfiles/htdocs/buyer-project/utils/**/*.{js,ts,mjs}","/Applications/XAMPP/xamppfiles/htdocs/buyer-project/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Applications/XAMPP/xamppfiles/htdocs/buyer-project/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Applications/XAMPP/xamppfiles/htdocs/buyer-project/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Applications/XAMPP/xamppfiles/htdocs/buyer-project/app.config.{js,ts,mjs}"]}},
{},
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;